global:
  scrape_interval: 60s
  scrape_timeout: 10s
  evaluation_interval: 60s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 60s
    scrape_timeout: 55s
    metrics_path: /metrics
    static_configs:
      - targets: ['172.23.0.4:9090']

  - job_name: nginx
    scrape_interval: 60s
    scrape_timeout: 55s
    metrics_path: /metrics
    static_configs:
      - targets: ['172.23.0.2:9113']

  - job_name: nginx_stub_status
    scrape_interval: 60s
    scrape_timeout: 55s
    metrics_path: /nginx_status
    static_configs:
      - targets: ['172.23.0.3:81']
